//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yastrebov_Glazki
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSale
    {
        public int ID { get; set; }
        public decimal Stoimost
        {
            get
            {
                decimal st = 0;
                if (Product != null)
                    st = Product.MinCostForAgent * ProductCount;
                return st;
            }
        }
        public int ProductID { get; set; }
        public int AgentID { get; set; }
        public System.DateTime SaleDate { get; set; }
        public int ProductCount { get; set; }
        public string ProductName
        {
            get
            {
                return Product.Title;
            }
        }

        public virtual Agent Agent { get; set; }
        public virtual Product Product { get; set; }
    }
}
